version: '3'

services:
  postgres:
    container_name: "pg-sandbox"
    build: ./postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d
  mysql:
    container_name: "mysql-sandbox"
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_DATABASE
    ports:
      - "3333:3306"
    volumes:
      - mysql-data:/var/lib/mysql/
      - ./init/mysql:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
    driver: local
  mysql-data:
    driver: local